#!/usr/bin/env bash
#shellcheck disable=SC1091
#
# Loads nvm, node, npm and npx
#

if
  [[ -z "${NVM_DIR:-}" && -z "${XDG_CONFIG_HOME:-}" ]] &&
    command -v brew > /dev/null 2>&1 &&
    [[ -n "$(brew --prefix nvm)" ]]
then
  NVM_DIR="$(brew --prefix nvm)"
elif [[ -z "${NVM_DIR:-}" && -z "${XDG_CONFIG_HOME:-}" ]]; then
  NVM_DIR="$HOME/.nvm"
elif [[ -z "${NVM_DIR:-}" ]]; then
  NVM_DIR="${XDG_CONFIG_HOME}/nvm"
fi
export NVM_DIR

# This loads nvm bash_completion which is bash and zsh
if [[ $SHELL == *"bash"* || $SHELL == *"zsh"* ]]; then
  [[ -s "${NVM_DIR}/bash_completion" ]] && \. "${NVM_DIR}/bash_completion"
fi

# Load only if installed
if [[ -r "${NVM_DIR}/nvm.sh" ]]; then
  . "${NVM_DIR}/nvm.sh" # This loads nvm, node, npm & npx
fi