version: "3.8"

services:
  db:
    image: postgres:13-alpine
    container_name: pgdb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: pgpassword
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: will@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 80:80

volumes:
  db-data: